name: Build and deploy Node.js app to Azure Web App - be-alfanevado

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # estable en Azure

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Build project
        run: npm run build

      # 👇 Migraciones ANTES de empaquetar
      - name: Apply database migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL_PROD: ${{ secrets.DATABASE_URL_PROD }}

      # 👇 Empaquetar todo en un zip listo para producción
      - name: Prepare artifact
        run: |
          mkdir output
          cp -r dist node_modules package*.json output/
          cd output
          zip -r ../release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'be-alfanevado'
          slot-name: 'Production'
          package: release.zip # 👈 aquí el zip, no la carpeta
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DBA683BB3DAF41749D5C4548B9A609AC }}