name: Build and deploy Node.js app to Azure Web App - be-alfanevado

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # 👈 mucho más estable que 22.x en Azure

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Generate Prisma client
        run: npx prisma generate

      # 👇 empaquetar solo lo necesario
      - name: Prepare artifact
        run: |
          mkdir output
          cp -r dist output/
          cp -r node_modules output/
          cp package*.json output/
          # Si usas .env en runtime, NO lo incluyas aquí

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: output

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .

      - name: Create .env file
        run: |
          echo "DATABASE_URL_PROD=${{ secrets.DATABASE_URL_PROD }}" > .env
          echo "Archivo .env creado con éxito."

      - name: Validate .env file
        run: cat .env

      - name: Apply database migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL_PROD: ${{ secrets.DATABASE_URL_PROD }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'be-alfanevado'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DBA683BB3DAF41749D5C4548B9A609AC }}